Added L0 tests and fixed some minor issues.
Azure/setup-helm pull request #20
Opened 2021-03-17 07:26 UTC by sundargs2000

[This if](https://github.com/Azure/setup-helm/blob/d315e938e1f5b9cfdd84a5d79fa9c652c7c2787b/src/run.ts#L111) never evaluates to true. 
![image](https://user-images.githubusercontent.com/33158091/111430247-1a026580-8720-11eb-95c7-567079562eae.png)

2021-03-22 15:20 UTC, Josh-01 requested changes

2021-03-25 16:50 UTC, sundargs2000 commented on src/run.ts
> +    if (filelist.length == 0) {
!filelist always evaluates to false as its an array.

2021-03-25 19:30 UTC, sundargs2000 commented on tsconfig.json
> +    // "esModuleInterop": true                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImpo
`esModuleInterop` has something to do with importing commonjs modules, it is causing some errors while mocking in ts-jest. By default, `esModuleInterop` is false and we aren't using any such imports as well. Almost all of our actions have this set to false as well.

2021-03-26 06:09 UTC, Josh-01 commented on src/run.ts
> +    if (filelist.length == 0) {
It is an array now, but if it is set as null somewhere later, this will cause a NPE in the if statement

2021-03-26 06:14 UTC, Josh-01 approved these changes
Add the null check and we should be good

2021-03-26 07:38 UTC, Josh-01 approved these changes

2021-03-26 07:38 UTC, merged